---
- name: Setup server 
  hosts: server
  remote_user: root
  gather_facts: no
  tasks:

###############################
#       SOFTWARE SETUP        #
###############################

  - name: Install aptitude
    apt:
      name: aptitude
      state: latest
      update_cache: true

  - name: Install software required for docker
    apt:
      pkg:
        - apt-transport-https
        - ca-certificates
        - curl
        - software-properties-common
        - python3-pip
        - virtualenv
        - python3-setuptools
      state: latest
      update_cache: true

  - name: Add Docker GPG apt Key
    apt_key:
      url: https://download.docker.com/linux/ubuntu/gpg
      state: present

  - name: Add Docker Repository
    apt_repository:
      repo: deb https://download.docker.com/linux/ubuntu focal stable
      state: present

  - name: Update apt and install docker-ce
    apt:
      name: docker-ce
      state: latest
      update_cache: true

  - name: Install Docker Module for Python
    pip:
      name: docker

###############################
#         DOCKER TEST         #
###############################

  - name: Pull default Docker image
    community.docker.docker_image:
      name: mariadb:latest
      source: pull

  - name: Create default containers
    community.docker.docker_container:
      name: db
      image: mariadb:latest
      state: present

###############################
#         UFW RULES           #
###############################

  - name: Deny trafic in
    ufw:
      default: deny
      direction: incoming

  - name: Allow trafic out
    ufw:
      default: allow
      direction: outgoing

  - name: Remove ssh
    ufw:
      delete: true
      rule: allow
      port: 22

  - name: Allow our ports
    ufw:
      rule: allow
      port: "{{ item }}"
      proto: tcp
    loop:
      - 22
      - 80
      - 443

  - name: Enable ufw
    ufw:
      state: enabled
