---
- name: Setup server 
  hosts: server
  remote_user: root

  vars:
    DB_USER: "wordpress"
    DB_PASS: "wordpress"
    DB_NAME: "wordpress"
    DB_HOST: "db"

  roles:
    - role: setup
      tags: setup
    - role: mariadb
      tags: mariadb
