---
- name: Setup server 
  hosts: server
  remote_user: root

  vars:
    DB_USER: "wordpress"
    DB_PASS: "wordpress"
    DB_NAME: "wordpress"
    DB_HOST: "db"
    WP_URL: "mpivet-p.42.fr"
    WP_TITLE: "mpivet-p"
    WP_ADMIN: "mpivet"
    WP_PASS: "wordpress"
    WP_MAIL: "mpivet-p@student.42madrid.com"

  roles:
    - role: setup
      tags: setup
    - role: mariadb
      tags: mariadb
    - role: phpmyadmin
      tags: phpmyadmin
    - role: wordpress
      tags: wordpress
