---
- hosts: all
  vars_files:
    - passwords.yml
    - vars.yml
  vars:
    ansible_python_interpreter: /usr/bin/python3

  roles:
    - common

#    - role: setup
#      tags: setup
#    - role: mariadb
#      tags: mariadb
#    - role: phpmyadmin
#      tags: phpmyadmin
#    - role: wordpress
#      tags: wordpress
#    - role: nginx
#      tags: nginx

# ansible-vault create passwords.yml
#passwords:
#  WP_PASS: "wordpress"
#  DB_PASS: "wordpress"
