---
- name: Copy necessary files to host
  ansible.builtin.copy:
    src: ./roles/wordpress/files/
    dest: /tmp/wordpress
    owner: root
    group: root
    mode: '0755'

- name: Build our wordpress image from the dockerfile with the config
  community.docker.docker_image:
    name: my_wordpress
    source: build
    build:
      path: /tmp/wordpress/

- name: Launch our container
  community.docker.docker_container:
    name: wordpress
    image: my_wordpress
    restart_policy: always
    env:
      DB_USER: "{{ DB_USER }}"
      DB_PASS: "{{ DB_PASS }}"
      DB_NAME: "{{ DB_NAME }}"
      DB_HOST: "{{ DB_HOST }}"
      WP_URL: "{{ WP_URL }}"
      WP_TITLE: "{{ WP_TITLE }}"
      WP_ADMIN: "{{ WP_ADMIN }}"
      WP_PASS: "{{ WP_PASS }}"
      WP_MAIL: "{{ WP_MAIL }}"
    networks:
      - name: inception
    volumes:
      - wp_data:/var/www/wordpress
