---
- name: Copy necessary files to host
  ansible.builtin.copy:
    src: ./roles/wordpress/files/
    dest: /tmp/wordpress
    owner: root
    group: root
    mode: '0755'

#Build first

- name: Remove file containing admin account and database passwords
  docker.builtin.file:
    path: /services/cloud-1/wordpress/install.sh
    state: absent

#Run
