---
- name: Copy Dockerfile to host
  ansible.builtin.copy:
    src: ./roles/phpmyadmin/files/Dockerfile
    dest: /services/cloud-1/phpmyadmin/

- name: Copy and modify phpmyadmin's config
  ansible.builtin.template:
    src: ./roles/phpmyadmin/files/config.inc.php.j2
    dest: /services/cloud-1/phpmyadmin/config.inc.php
    mode: 0666

#Build container first

- name: Remove file containing database's password
  docker.builtin.file:
    path: /services/cloud-1/phpmyadmin/config.inc.php
    state: absent
