---
- name: Copy docker-compose to host
  tags: [setup, copy, docker]
  ansible.builtin.copy:
    src: ./roles/common/files/docker-compose.yml
    dest: /services/cloud-1/

- name: Copy mariadb files to host
  tags: [setup, copy, mariadb]
  ansible.builtin.copy:
    src: ./roles/common/files/mariadb
    dest: /services/cloud-1/
    owner: root
    group: root
    mode: '0755'

- name: Copy PMA's Dockerfile to host
  tags: [setup, copy, phpmyadmin]
  ansible.builtin.copy:
    src: ./roles/common/files/phpmyadmin/Dockerfile
    dest: /services/cloud-1/phpmyadmin/

- name: Copy and modify phpmyadmin's config
  tags: [setup, copy, phpmyadmin]
  ansible.builtin.template:
    src: ./roles/common/files/phpmyadmin/config.inc.php.j2
    dest: /services/cloud-1/phpmyadmin/config.inc.php
    mode: 0666

- name: Copy wordpress necessary files to host
  tags: [setup, copy, wordpress]
  ansible.builtin.copy:
    src: ./roles/common/files/wordpress
    dest: /services/cloud-1/
    owner: root
    group: root
    mode: '0755'

- name: Copy nginx Dockerfile to host
  tags: [setup, copy, nginx]
  ansible.builtin.copy:
    src: ./roles/common/files/nginx/Dockerfile
    dest: /services/cloud-1/nginx/

- name: Copy nginx conf directory
  tags: [setup, copy, nginx]
  ansible.builtin.copy:
    src: ./roles/common/files/nginx/conf
    dest: /services/cloud-1/nginx/

- name: Copy and modify nginx's config
  tags: [setup, copy, nginx]
  ansible.builtin.template:
    src: ./roles/common/files/nginx/template/nginx.conf.j2
    dest: /services/cloud-1/nginx/conf/nginx.conf
    mode: 0664

- name: Copy .env file
  tags: [setup, copy]
  ansible.builtin.template:
    src: ./roles/common/files/.env.j2
    dest: /services/cloud-1/.env
    mode: 0664

