---
- name: Create the directories where the volumes are going to be accessible
  tags: [setup, volumes]
  ansible.builtin.file:
    path: "/root/data/{{ item }}"
    state: directory
    mode: 0755
  loop:
    - wordpress
    - database
    - phpmyadmin
