---
- name: Build mariadb container
  tags: [mariadb, build]
  community.docker.docker_compose:
    project_src: /services/cloud-1/
    project_name: cloud-1
    services:
      - db
    build: true
    stopped: true
